### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by DusKing1** [DusKing1/PID-Evaluator#6]
- [ ] re-build the PSD custom function
- [ ] 2-D PSD on gyro_scaled and gyro_ADC
- [ ] pre-filter dterm and dterm
- [ ] 10*log10 instead of log10 in PSD
- [ ] change PSD scale range to +10 ~ -35 dbm
- [ ] display the frequency response of the whole system
- [ ] show the P, I and D frequency plot in 2-D form
- [ ] time-frequency analysis with STFT method
- [ ] support FFT_FREQ debug mode
- [ ] Re-write I/O delay measurement algorithm
- [ ] public the basic python approach of fuzzy pid analysis

Dividing different functions into separate notebooks
- [ ] step responce
- [ ] I/O delay distinguished by setpoint
- [ ] filter delay  distinguished by throttle
- [ ] time-freq analysis
- [ ] noise plot (2D and 3D)
